### ISSUE TITLE
Code For FCM server

### ISSUE THREAD

**Issue by Mushtaq123** [SimonMarquis/FCM-toolbox#1]
Hi Sir,

Where can I find the Source for FCM Server

**Comment by SimonMarquis** [comment]
Hi @Mushtaq123,
There is no source code for the FCM server.
FCM server is own by Google, and the only endpoint I use is `https://fcm.googleapis.com/fcm/send`.  
The documentation can be found [here](https://firebase.google.com/docs/cloud-messaging/http-server-ref).
