### ISSUE TITLE
No token, just ```MISSING_INSTANCEID_SERVICE```

### ISSUE THREAD

**Issue by StephanoGeorge** [SimonMarquis/FCM-toolbox#10]
I get `MISSING_INSTANCEID_SERVICE` in titlebar and toast.

How can I debug?

I use microG. FCM-toolbox did not registered, but some other apps can receive message.

**Versions**

- FCM toolbox : 1.8.4
- microG Services Core : 0.2.22.212658
- microG Services Framework Proxy : 0.1.0

**Comment by SimonMarquis** [comment]
Hi, 
I found references to this error [here](https://developers.google.com/android/reference/com/google/android/gms/iid/InstanceID#public-static-final-string-error_missing_instanceid_service).

```
public static final String ERROR_MISSING_INSTANCEID_SERVICE
Tokens can't be generated. Only devices with Google Play are supported.
Constant Value: "MISSING_INSTANCEID_SERVICE"
```

It seems that a proper Google Play Services installation is required for this to work correctly.
