### ISSUE TITLE
display connected device

### ISSUE THREAD

**Issue by mmck345** [SimonMarquis/FCM-toolbox#12]
I cloned the project the system works amazing! Thank you!
If I understood correctly I should see on the messaging page, all the devices connected to the app, can you understand why I do not see the connected devices?

I want to point out that once I connect to the app on the phone, the connection appears in the Realtime Database, but is not updated in my web app.

![image](https://user-images.githubusercontent.com/52917429/149433779-14bb03bd-f45e-4879-9101-2ffc782dccd0.png)

Thank you very much 👍

**Comment by SimonMarquis** [comment]
For that you need to update the configuration of the web app, especially the Firebase Realtime Database url.

https://github.com/SimonMarquis/FCM-toolbox#configuration-1

**Comment by SimonMarquis** [comment]
![U4YWT4xu1I](https://user-images.githubusercontent.com/1921278/149577990-7ad3ac77-cfd4-461b-8b2a-8e74418bba53.png)

![sZb5gpwVYY](https://user-images.githubusercontent.com/1921278/149578083-5e44c7b7-ba0b-46db-92a0-d67ab1f85994.png)

**Comment by mmck345** [comment]
Thank you!
It works great for me!
