### ISSUE TITLE
The website seems to have some minor issues

### ISSUE THREAD

**Issue by TwilightKHQ** [SimonMarquis/FCM-toolbox#199]
https://fcm-toolbox-public.web.app/

![1720689608988](https://github.com/SimonMarquis/FCM-toolbox/assets/25874642/b9ed110a-8093-473a-b0e1-c07ea387352c)

**Comment by SimonMarquis** [comment]
Make sure you don't have any ad blocker that incorrectly blocks CSS requests.
Everything loads fine using remote endpoints like https://www.webpagetest.org/.
