### ISSUE TITLE
firebase push credentials

### ISSUE THREAD

**Issue by vortexsystems** [SimonMarquis/FCM-toolbox#253]
Hi Simon, great toolbox, seems to work well.  If I wanted to use the android app that is already at the playstore but send push notifications from my python application is that possible?  What credentials would I need to send data on a topic that the android app is subscribed to?

**Comment by SimonMarquis** [comment]
Hi @vortexsystems, unfortunately the recent change to [FCM HTTP v1 API](https://firebase.google.com/docs/cloud-messaging/migrate-v1) means that a Google Cloud credential is now required, and I won't make it public.
I can suggest you to clone this repository and provide your own credentials.
