### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by encedo** [SimonMarquis/FCM-toolbox#5]
Hi Simon,
great tool! However, I have a suggestion: is it hard for you to add a feature to receive notification when app is background? 

Currently, even when app is running (is on task list) after sometime app disconnect from FCM service (app icon not green).

It would be very helpful is app could be running in the background (as a service) and receive notification even when the phone is locked- just like Signal or Whatsapp do.

Regards
Chris

**Comment by SimonMarquis** [comment]
Hi Chris.
> It would be very helpful is app could be running in the background (as a service)

Unforunately this is not what this project is about (it is only a toolbox).

> and receive notification even when the phone is locked- just like Signal or Whatsapp do.

It already does receive notificatons when the app is in background and even when the app process is killed by the system. You simply have to configure the notificaiton priority to `high` (in the settings tab on the web app).

**Comment by SimonMarquis** [comment]
Also,
> Currently, even when app is running (is on task list) after sometime app disconnect from FCM service (app icon not green).

This is the expected behaviour. The green indicator is only meant to flag "active" users. See https://firebase.google.com/docs/database/android/offline-capabilities#section-sample for reference.
