### ISSUE TITLE
How to broadcast notification to All Apps without spesific token

### ISSUE THREAD

**Issue by indraAsLesmana** [SimonMarquis/FCM-toolbox#6]

**Comment by SimonMarquis** [comment]
To do that, you can use [topics](https://firebase.google.com/docs/cloud-messaging/android/topic-messaging).
All devices should subscribe to this topic, then you can send messages to this topic identifier instead of specific device tokens.

**Comment by Decryptor24** [comment]
Where i can change your library please tell me details??
