### ISSUE TITLE
self-compiled FCM-toolbox crash while receiving notification

### ISSUE THREAD

**Issue by xdujiang** [SimonMarquis/FCM-toolbox#64]
**What I have done**

1. Git clone the project, download google-services.json, replace the original one in app folder, compile using Android studio 2022.2.1
2. Launch FCM-toolbox app, get token
3. Configurate the FCM-toolbox webpage with my Cloud Messaging API (Legacy)  and Realtime Database url and the device token

**What happened**

1. The indicator of FCM-toolbox is green
2. While I click the "Sent" botton on the webpage, it shows 

> {
>   "to": "token",
>   "time_to_live": 60,
>   "priority": "high",
>   "data": {
>     "ping": {}
>   }
> }
> {
>   "multicast_id": xxxxxxx,
>   "success": 1,
>   "failure": 0,
>   "canonical_ids": 0,
>   "results": [
>     {
>       "message_id": "0:xxxxxxx"
>     }
>   ]
> }

3. The APP on my phone crash, possibly related logcat

> E AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
> E AndroidRuntime: Process: fr.smarquis.fcm, PID: 6444
> E AndroidRuntime: java.lang.IllegalArgumentException: Cannot serialize abstract class k5.a
> E AndroidRuntime:        at e5.a.a(SourceFile:29)
> E AndroidRuntime:        at e5.d0.c(SourceFile:163)
> E AndroidRuntime:        at e5.d0.a(SourceFile:4)
> E AndroidRuntime:        at fr.smarquis.fcm.services.FcmService.c(SourceFile:319)
> E AndroidRuntime:        at com.google.firebase.messaging.FirebaseMessagingService.b(SourceFile:846)
> E AndroidRuntime:        at androidx.emoji2.text.n.run(SourceFile:88)
> E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> E AndroidRuntime:        at p1.n.run(SourceFile:26)
> E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)

**Enviroment:**
* Sender: 
    * FCM-toolbox webpage

* Receiver: 
    * Android 12, with self configurated and compiled FCM-toolbox

* FCM config:
    * Messaging:
        * Add package fr.smarquis.fcm
        * Enable Cloud Messaging API (Legacy) 
    * Realtime Database:
        * Create new database
        * Set rules for read and write to be "true"

I tried the official FCM-toolbox, everything works well.

Sorry but I'm new to FCM and android, is there anything wrong with my config?

**Comment by SimonMarquis** [comment]
Hi @xdujiang, thanks for the detailed report.
It seems like I accidentally removed the Moshi codegen dependency in the previous cleanup commit: https://github.com/SimonMarquis/FCM-toolbox/commit/f190c7f09fae052f230192e77878287475660c3d#diff-8cff73265af19c059547b76aca8882cbaa3209291406f52df1dafbbc78e80c46L77-R93

It should be fixed now.

**Comment by xdujiang** [comment]
Thanks, it works like a charm now :satisfied:
