### ISSUE TITLE
Is it possible to migrate to Firebase Cloud Messaging API?

### ISSUE THREAD

**Issue by TwilightKHQ** [SimonMarquis/FCM-toolbox#68]
I just started using Firebase recently, the default configuration of Firebase is Firebase Cloud Messaging API, and it took me a while to find the API key for Cloud Messaging API.
Planning to migrate from Cloud Messaging API to Firebase Cloud Messaging API?

**Comment by SimonMarquis** [comment]
I'm not sure what you are referring to. Can you link to some documentation about the differences between these 2 APIs?

**Comment by TwilightKHQ** [comment]
https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by SimonMarquis** [comment]
Thanks for the link.
Unfortunately it seems like the new integration would require a significant amount of refactor, especially the new authentication mechanism.
I'm open to PRs but I don't think I'll have time to migrate this on my own.

**Comment by SimonMarquis** [comment]
Hi @TwilightKHQ, I've finally taken some time to migrate this project.
It now uses the HTTP v1 API.

The public instance is now hosted on:
- https://fcm-toolbox-public.web.app/
- https://fcm-toolbox-public.firebaseapp.com/

**Comment by TwilightKHQ** [comment]
Great job. Thanks for doing this.
