### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by aborichevsky** [SimonMarquis/FCM-toolbox#8]
Hi! I want to rebuild your app with my FCM credentials but i have an error "No matching client found for package name 'fr.smarquis.fcm'"
What i do wrong? i build it throught Android Studio using Build tab. Thanks!

**Comment by SimonMarquis** [comment]
It'explained here: https://github.com/SimonMarquis/FCM-toolbox#configuration
You must provide your own `google-services.json` file.

**Comment by aborichevsky** [comment]
> It'explained here: https://github.com/SimonMarquis/FCM-toolbox#configuration
> You must provide your own `google-services.json` file.

I provided it. I moved my google-services.json file to /app directory with replacement of default

**Comment by SimonMarquis** [comment]
Did you set the proper `package_name`? `fr.smarquis.fcm`

**Comment by aborichevsky** [comment]
Sorry. Problem resolved. I configure wrong package name while setup file in firebase console. Thank you for support
